apiVersion: v1
kind: Service
metadata:
  name: sasara-server
spec:
  selector:
    app: sasara-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
